"use strict";

/**
 * @ngdoc function
 * @name contractualClienteApp.decorator:TextTranslate
 * @description
 * # TextTranslate
 * Decorator of the contractualClienteApp
 */
var text_es = {
  BTN: {
    VER: "Ver",
    SELECCIONAR: "Seleccionar",
    CANCELAR: "Cancelar",
    CONFIRMAR: "Confirmar",
    AGREGAR: "Agregar",
    REGISTRAR: "Registrar",
    SOLICITAR_RP:"Solicitar RP",
    QUITAR_RUBRO: "Quitar",
    VER_SEGUIMIENTO_FINANCIERO:"Ver seguimiento financiero",
    BUSCAR: "Buscar",
  },
  TITULO: "GENERATOR-OAS",
  MENSAJE_INICIAL: "Ahora puede comenzar con el desarrollo ...",
  NECESIDADES: "Necesidades",
  NECESIDAD: "Necesidad",
  SOLICITUD: "Solicitud",
  UNIVERSIDAD_NOMBRE:"Universidad Distrital Francisco José de Caldas",

  //SOLICITUD RP
  ERROR: "Error",
  SALIR:"Salir",
  VOLVER_CONTRATOS: "Volver a contratos",
  CONTRATO_CANCELADO: "Contrato cancelado",
  CONTRATO_FINALIZADO: "Contrato finalizado",
  NUMERO_SOLICITUD:"Número solicitud",
  INSERCION_RP:"Se insertó correctamente la solicitud del registro presupuestal con los siguientes datos",
  VIGENCIA_SOLICITUD: "Vigencia solicitud",
  FECHA_SOLICITUD: "Fecha solicitud",
  NUMERO_CONTRATO: "Número contrato",
  SELECCIONE_UNA_VIGENCIA:"Seleccione una vigencia diferente",
  RESPONSABLE_DOCUMENTO: "Responsable documento",
  RESPONSABLE: "Responsable",
  DATOS_APROPIACIONES: "Datos de las apropiaciones",
  MODALIDAD_SELECCION: "Modalidad Selección",
  CONTRATO: "Contrato",
  VIGENCIA_CONTRATO: "Vigencia contrato",
  FUENTE:"Fuente",
  SOLICITUD_PERSONAS:"Contratos para solicitud del registro presupuestal",
  VIGENCIA_ACTUAL:"Vigencia Actual ",
  VIGENCIA_SELECCIONADA:"Vigencia Seleccionada ",
  SELECCION_CDP:"Selección de CDP",
  UNIDAD_EJECUTORA:"Unidad ejecutora",
  ESTADO:"Estado",
  SELECCION_COMPROMISO:"Selección de Compromiso",
  SOLICITUD_RP: "Solicitud Registro Presupuestal",
  DATOS_RP:"Datos del Registro Presupuestal",
  BENEFICIARIO:"Beneficiario",
  NOMBRE_CONTRATISTA: "Nombre",
  DOCUMENTO_CONTRATISTA: "No Documento",
  NOMBRE: "Nombre",
  FUENTE_FINANCIAMIENTO: "Fuente Financiamiento",
  VALOR: "Valor",
  VALOR_DESEMBOLSADO: "Valor desembolsado",
  COMPROMISO: "Compromiso",
  NUMERO:"Número",
  VIGENCIA:"Vigencia",
  COMPROMISO_TIPO:"Tipo",
  VALOR_RP:"Valor registro presupuestal",
  SALDO_AP:"Saldo apropiación",
  SALDO_A_FAVOR_CONTRATISTA:"Saldo a favor del contratista",
  SALDO_A_FAVOR_UNIVERSIDAD:"Saldo a favor de la Universidad",
  CDP:"CDP",
  CODIGO: "Codigo",
  CONSECUTIVO:"Consecutivo",
  OBJETIVO:"Objetivo",
  OBJETO:"Objeto",
  ORDENADOR:"Ordenador",

  //SEGUMIENTO FINANCIERO
  SEGUIMIENTO_FINANCIERO:"Seguimiento financiero del contrato",
  DATOS_CONTRATO:"Datos contrato",
  ORDENES_PAGO: "Ordenes pago",
  ESTADISTICAS : "Estadisticas",
  DATOS_FINANCIEROS_CONTRATO: "Datos financieros del contrato",
  DATOS_CONTRATISTA: "Datos contratista",
  APELLIDOS: "Apellidos",
  NOMBRES: "Nombres",
  TIPO_DOCUMENTO: "Tipo documento",
  NUMERO_DOCUMENTO : "No documento",
  FECHA_INICIO:"Fecha inicio",
  FECHA_FIN:"Fecha fin",
  DATOS_REGISTRO_PRESUPUESTAL:"Datos del registro presupuestal",
  NUMERO_REGISTRO_PRESUPUESTAL: "No RP",
  NOMBRE_REGISTRO_PRESUPUESTAL: "Nombre RP",
  NUMERO_DISPONIBILIDAD: "No CDP",
  NOMBRE_DISPONIBILIDAD: "Nombre CDP",
  ORDEN_PAGO: "Orden pago",
  FECHA_ORDEN: "Fecha orden",
  VALOR_BRUTO: "Valor bruto",
  LINEA_ORDEN_PAGO:"Linea del tiempo de ordenes de pago",
  ESTADISTICAS_GENERALES: "Estadisticas generales",
  VALOR_TOTAL_CONTRATO: "Valor total contrato",
  VALOR_MENSUAL: "Valor mensual",
  VALOR_TOTAL_PAGADO:"Valor total pagado",
  VALOR_RESTANTE:"Valor restante",
  PORCENTAJE_PAGADO:"Porcentaje pagado",
  PORCENTAJE_RESTANTE:"Porcentaje restante",
  GRAFICO_BARRAS_CONTRATO:"Grafico de barras del contrato",
  CARGO:"Cargo",

  //SEGUIMIENTO LEGAL
  NOVEDADES: "Novedades",
  SEGUIMIENTO_LEGAL: "Seguimiento Legal",
  SELECCIONE_UNA_NOVEDAD: "Por favor seleccione la novedad",
  CREAR_NOVEDAD_ADICION_PRORROGA: "Crear Novedad de Adición y/o Prorroga",
  CREAR_ACTA_INICIO: "Crear Acta de Inicio",
  CREAR_NOVEDAD_SUSPENSION: "Crear Novedad de Suspensión",
  CREAR_NOVEDAD_REINICIO: "Crear Novedad de Reinicio",
  CREAR_NOVEDAD_CESION: "Crear Novedad de Cesión",
  CREAR_NOVEDAD_LIQUIDACION: "Crear Novedad de Liquidación",
  FECHA_TERMINACION_ANTICIPADA: "Fecha Terminación Anticipada",
  CREAR_NOVEDAD_TERMINACION_ANTICIPADA: "Crear Novedad de Terminación Anticipada",
  CREAR_NOVEDAD_TERMINACION_BILATERAL: "Crear Novedad de Terminación Anticipada",
  CREAR_NOVEDAD_OTRO_SI_MODIFICATORIO: "Crear Otro Sí Modificatorio",
  CREAR_NOVEDAD_OTRO_SI_ACLARATORIO: "Crear Otro Sí Aclaratorio",

  //ACTA INICIO
  ACTA_INICIO: "ACTA DE INICIO",
  INFORMACION_ACTA_INICIO: "INFORMACIÓN",
  PLAZO_MESES: "Plazo (en meses)",
  SUPERVISOR: "Supervisor",
  NO_REGISTRA_ACTA_INICIO: "No registra",
  NUMERO_POLIZA: "Número de poliza",
  FECHA_EXPEDICION_POLIZA: "Fecha Expedición de Póliza",
  FECHA_APROBACION_POLIZA: "Fecha Aprobación de Póliza",
  INFORMACION_NOVEDAD: "INFORMACIÓN DE LA NOVEDAD",
  INVENTARIO: "INVENTARIO",
  TIPO_BIEN: "TIPO DE BIEN",
  PLACA: "PLACA",
  DESCRIPCION: "DESCRIPCIÓN",
  SEDE: "SEDE",
  DEPENDENCIA: "DEPENDENCIA",
  ESTADO_DEL_BIEN: "ESTADO DEL BIEN",
  TIEMPO_CONTRATO: "Tiempo contrato (Días)",

  //ACTA DE ADICION/PRORROGA
  ACTA_ADICION_PRORROGA: "ACTA DE ADICIÓN / PRORROGA",
  TIPO_CONTRATO: "Tipo de contrato",
  PLAZO_INICIAL_MESES: "Plazo inicial (En meses)",
  FECHA_INICIACION: "Fecha de Iniciación",
  ADICION: "Adición",
  PRORROGA: "Prórroga",
  MOTIVO: "Motivo",
  MOTIVO_NOVEDAD: "Ingrese aqui el motivo de la novedad",
  INFORMACION_NOVEDAD_ADICION: "INFORMACIÓN DE ADICIÓN",
  NUMERO_CDP: "Número CDP",
  VALOR_ADICION: "Valor Adición",
  FECHA_ADICION: "Fecha Adición",
  NUEVO_VALOR_CONTRATO: "Nuevo Valor del Contrato",
  VALOR_ADICION_TEXTO: "Valor Adición en Letras",
  NUEVO_VALOR_ADICION: "Nuevo Valor en Letras",
  INFORMACION_NOVEDAD_PRORROGA: "INFORMACIÓN DE PRÓRROGA",
  TIEMPO_PRORROGA: "Tiempo Prórroga (Días)",
  TIEMPO_PRORROGA_PLACEHOLDER: "En días",
  FECHA_PRORROGA: "Fecha Prórroga",
  NUEVO_PLAZO_CONTRATO: "Nuevo Plazo del Contrato",
  NUEVO_PLAZO_CONTRATO_PLACEHOLDER: "Nuevo plazo del contrato (En meses)",
  MENSAJE_MESES: "MESES Y",
  MESES: "MESES",
  MES: "MES",
  DIAS: "DÍAS",
  DIA: "DÍA",
  UN: "UN",
  DOS: "DOS",
  TRES: "TRES",
  CUATRO: "CUATRO",
  CINCO: "CINCO",
  SEIS: "SEIS",
  SIETE: "SIETE",
  OCHO: "OCHO",
  NUEVE: "NUEVE",
  DIEZ: "DIEZ",
  ONCE: "ONCE",
  DOCE: "DOCE",
  TRECE: "TRECE",
  CATORCE: "CATORCE",
  QUINCE: "QUINCE",
  DIECISEIS: "DIECISÉIS",
  DIECISIETE: "DIECISIETE",
  DIECIOCHO: "DIECIOCHO",
  DIECINUEVE: "DIECINUEVE",
  DIECI: "DIECI",
  VEINTE: "VEINTE",
  VEINTI: "VEINTI",
  TREINTA: "TREINTA",
  CUARENTA: "CUARENTA",
  CINCUENTA: "CINCUENTA",
  SESENTA: "SESENTA",
  SETENTA: "SETENTA",
  OCHENTA: "OCHENTA",
  NOVENTA: "NOVENTA",
  Y: " Y ",
  CIENTO: "CIENTO ",
  CIEN: "CIEN",
  DOSCIENTOS: "DOSCIENTOS ",
  TRESCIENTOS: "TRESCIENTOS ",
  CUATROCIENTOS: "CUATROCIENTOS ",
  QUINIENTOS: "QUINIENTOS ",
  SEISCIENTOS: "SEISCIENTOS ",
  SETECIENTOS: "SETECIENTOS ",
  OCHOCIENTOS: "OCHOCIENTOS ",
  NOVECIENTOS: "NOVECIENTOS ",
  UNMIL: "UN MIL",
  MIL: "MIL",
  UNMILLON: "UN MILLON",
  MILLONES: "MILLONES",
  PESOS: "PESOS",
  PESO: "PESO",
  CON: "CON ",
  CERO: "CERO ",

  //ACTA DE CESION
  ACTA_CESION: "ACTA DE CESIÓN",
  INFORMACION:"INFORMACIÓN",
  NO_REGISTRA:"No Registra",
  VALOR_CONTRATO:"Valor del contrato",
  CONTRATANTE:"Contratante",
  CONTRATISTA:"Contratista",
  ORDENADOR_DE_GASTO:"Ordenador de gasto",
  CEDULA_CESIONARIO:"Cédula cesionario",
  TIPO_PERSONA: "Tipo persona",
  PERSONA_NATURAL: "Natural",
  NUMERO_OFICIO:"Número oficio",
  NUMERO_OFICIO_ESTADO_CUENTAS:"Número oficio estado de cuentas",
  FECHA_OFICIO:"Fecha oficio",
  FECHA_CESION:"Fecha cesión",
  OTRAS_OBSERVACIONES:"Otras observaciones",
  INFORMACION_CESIONARIO:"INFORMACIÓN CESIONARIO",
  SELECCIONAR_CESIONARIO:"Seleccionar cesionario",
  SELECCIONAR_CONTRATO:"Seleccionar contrato",
  ACTA_REINICIO:"ACTA DE REINICIO",
  FECHA_SUSPENSION:"Fecha suspension",
  FECHA_REINICIO:"Fecha reinicio",
  PERIODO_SUSPENSION:"Periodo suspension (Días)",
  ACTA_SUSPENSION:"ACTA DE SUSPENSIÓN",
  MOTIVO_SUSPENSION:"Motivo de suspensión",
  CAMPO_REQUERIDO:"Este campo es obligatorio",

  //ALERTAS
  TITULO_ERROR:"Errores en el formulario",
  TITULO_ADVERTENCIA:"Advertencia",
  DESCRIPCION_ADVERTENCIA: "Primero debe seleccionar un tipo de novedad!",
  DESCRIPCION_ADVERTENCIA_ADICION: "El valor de la adición no puede ser superior al 50% del valor del contrato.",
  DESCRIPCION_ADVERTENCIA_PRORROGA: "El valor de la prórroga no puede ser superior al 50% del tiempo de ejecución del contrato.",
  DESCRIPCION_ERROR:"Llenar los campos obligatorios en el formulario",
  DESCRIPCION_ERROR_LEGAL:"Contrato no encontrado",
  TITULO_BUEN_TRABAJO:"¡Buen trabajo!",
  DESCRIPCION_INICIO:"Se registro exitosamente la novedad de 'Acta de inicio'<br>al contrato # ",
  DESCRIPCION_ADICION:"Se registro exitosamente la novedad de 'Adición'<br>al contrato # ",
  DESCRIPCION_PRORROGA:"Se registro exitosamente la novedad de 'Prorroga'<br>al contrato # ",
  DESCRIPCION_ADICION_PRORROGA:"Se registro exitosamente la novedad de 'Adición y Prorroga'<br>al contrato # ",
  DESCRIPCION_INICIO_1:"El estado del presente contrato se actualizo a 'Ejecución'.",
  DESCRIPCION_INICIO_ERROR_FECHA:"La fecha fin debe ser mayor a la fecha inicio!",
  DESCRIPCION_CESION:"Se registro exitosamente la novedad de cesión al contrato # ",
  DESCRIPCION_SUSPENSION:"Se registro exitosamente la novedad de suspensión al contrato # ",
  DESCRIPCION_REINICIO:"Se registro exitosamente la novedad de reinicio al contrato # ",
  DESCRIPCION_ACTA_CESION:"Acta de inicio para cesionario del contrato",
  ANIO:" vigencia "

};

var text_en = {
  TITULO: "GENERATOR-OAS",
  MENSAJE_INICIAL: "Now get to start to develop ...",
  NECESIDADES: "Needs",
  NECESIDAD: "Need",
  BTN: {
    VER: "See",
    SELECCIONAR: "Choose",
    CANCELAR: "Cancel",
    CONFIRMAR: "Confirm",
    AGREGAR: "Add",
    REGISTRAR: "Register",
    SOLICITAR_RP:"RP request",
    QUITAR_RUBRO: "Delete",
    VER_SEGUIMIENTO_FINANCIERO:"See financial monitoring",
    BUSCAR: "Search",
  },

  //SOLICITUD RP
  ERROR: "Error",
  SALIR:"Exit",
  VOLVER_CONTRATOS: "Back to contracts",
  UNIVERSIDAD_NOMBRE:"Universidad Distrital Francisco José de Caldas",
  NUMERO_SOLICITUD:"Request number",
  INSERCION_RP:"The budget register request was insert correctly with the following data:",
  VIGENCIA_SOLICITUD: "Request validity",
  FECHA_SOLICITUD: "Request date",
  NUMERO_CONTRATO: "Contract number",
  RESPONSABLE_DOCUMENTO: "Person responsible identification",
  SELECCIONE_UNA_VIGENCIA:"Choose a diferent validity",
  RESPONSABLE: "Person responsible",
  DATOS_APROPIACIONES: "Appropiation data",
  MODALIDAD_SELECCION: "Selection method",
  CONTRATO: "Contract",
  VIGENCIA_CONTRATO: "Contract validity",
  CONTRATO_CANCELADO: "Canceled contract",
  CONTRATO_FINALIZADO: "Ended contract",
  FUENTE:"Source",
  TIPO_PERSONA: "Person type",
  SOLICITUD_PERSONAS:"Contracts for budget registers",
  VIGENCIA_ACTUAL:"Current validity",
  VIGENCIA_SELECCIONADA:"Chosen validity ",
  SELECCION_CDP:"CDP choise",
  UNIDAD_EJECUTORA:"Performer unity",
  ESTADO:"State",
  SELECCION_COMPROMISO:"Agreement choose",
  SOLICITUD_RP: "Budget register request",
  DATOS_RP:"Buget register data",
  BENEFICIARIO:"Beneficiary",
  NOMBRE_CONTRATISTA: "Name",
  DOCUMENTO_CONTRATISTA: "Identification",
  NOMBRE: "Name",
  FUENTE_FINANCIAMIENTO: "Funding source",
  VALOR: "Value",
  COMPROMISO: "Agreement",
  NUMERO:"Number",
  VIGENCIA:"Validity",
  COMPROMISO_TIPO:"Tipe",
  VALOR_RP:"Budget register value",
  SALDO_AP:"Appropiation reminder",
  SALDO_A_FAVOR_CONTRATISTA:"Balance in favor of the contractor",
  SALDO_A_FAVOR_UNIVERSIDAD:"Balance in favor of the University",
  CDP:"CDP",
  CODIGO: "Code",
  CONSECUTIVO:"Consecutive",
  OBJETIVO:"Objective",
  OBJETO:"Object",
  ORDENADOR:"Authorizer",

  //SEGUMIENTO FINANCIERO
  SEGUIMIENTO_FINANCIERO:"Financial monitoring of the contract",
  DATOS_CONTRATO:"Contract data",
  ORDENES_PAGO: "Pay orders",
  ESTADISTICAS : "Statistics",
  DATOS_FINANCIEROS_CONTRATO: "Financial data of the contract",
  DATOS_CONTRATISTA: "Contractor data",
  APELLIDOS: "Surnames",
  NOMBRES: "Names",
  TIPO_DOCUMENTO: "Identification type",
  NUMERO_DOCUMENTO : "Document number",
  FECHA_INICIO:"Start date",
  FECHA_FIN:"End date",
  DATOS_REGISTRO_PRESUPUESTAL:"Budget register data",
  NUMERO_REGISTRO_PRESUPUESTAL: "Budget register number",
  NOMBRE_REGISTRO_PRESUPUESTAL: "Budget register name",
  NUMERO_DISPONIBILIDAD: "Availability number",
  NOMBRE_DISPONIBILIDAD: "Availability name",
  ORDEN_PAGO: "Pay order",
  FECHA_ORDEN: "Order date",
  VALOR_BRUTO: "Gross value",
  LINEA_ORDEN_PAGO:"Pay orders timeline",
  ESTADISTICAS_GENERALES: "General statistics",
  VALOR_TOTAL_CONTRATO: "Contract total value",
  VALOR_MENSUAL: "Monthly value",
  VALOR_TOTAL_PAGADO:"Paid total value",
  VALOR_RESTANTE:"Remaining value",
  PORCENTAJE_PAGADO:"Paid percentage",
  PORCENTAJE_RESTANTE:"Remaining percentage",
  GRAFICO_BARRAS_CONTRATO:"Contract bar graph",
  CARGO:"Post",

  //SEGUIMIENTO LEGAL
  NOVEDADES: "Novelty",
  DESCRIPCION_ERROR_LEGAL:"Imposible to find contract",
  SEGUIMIENTO_LEGAL: "Legal Tracking",
  SELECCIONE_UNA_NOVEDAD: "Please select the novelty",
  CREAR_NOVEDAD_ADICION_PRORROGA: "Create Novelty Addition and / or Extension",
  CREAR_ACTA_INICIO: "Create Minutes of Beginning",
  CREAR_NOVEDAD_SUSPENSION: "Create Novelty Suspension",
  CREAR_NOVEDAD_REINICIO: "Create Novelty Restart",
  CREAR_NOVEDAD_CESION: "Create Novelty Assignment",
  CREAR_NOVEDAD_LIQUIDACION: "Create Novelty Clearance",
  FECHA_TERMINACION_ANTICIPADA: "Date Early Termination",
  CREAR_NOVEDAD_TERMINACION_ANTICIPADA: "Create Novelty Early Termination",
  CREAR_NOVEDAD_TERMINACION_BILATERAL: "Create Novelty of Early Termination",
  SELECCIONAR_CONTRATO:"Choose contract",
  CREAR_NOVEDAD_OTRO_SI_MODIFICATORIO: "Create Other Yes Modification",
  CREAR_NOVEDAD_OTRO_SI_ACLARATORIO: "Create Other Yes Clear",

  //ACTA INICIO
  ACTA_INICIO: "HOME ACT",
  INFORMACION_ACTA_INICIO: "INFORMATION",
  PLAZO_MESES: "Term (in months)",
  SUPERVISOR: "Supervisor",
  NO_REGISTRA_ACTA_INICIO: "Not register",
  NUMERO_POLIZA: "Policy number",
  FECHA_EXPEDICION_POLIZA: "Date Policy Issue",
  FECHA_APROBACION_POLIZA: "Date Policy Approval",
  INFORMACION_NOVEDAD: "NOVELTY INFORMATION",
  INVENTARIO: "INVENTORY",
  TIPO_BIEN: "TYPE OF PROPERTY",
  PLACA: "LICENSE PLATE",
  DESCRIPCION: "DESCRIPTION",
  SEDE: "HEADQUARTERS",
  DEPENDENCIA: "DEPENDENCE",
  ESTADO_DEL_BIEN: "STATE OF POSSESSION",
  TIEMPO_CONTRATO: "Contract time (Days)",

  //ACTA DE ADICION/PRORROGA
  ACTA_ADICION_PRORROGA: "ADDITION / EXTENSION ACT",
  TIPO_CONTRATO: "Type of contract",
  PLAZO_INICIAL_MESES: "Initial period (In months)",
  FECHA_INICIACION: "Date of Initiation",
  ADICION: "Addition",
  PRORROGA: "Extension",
  MOTIVO: "Reason",
  MOTIVO_NOVEDAD: "Enter here the reason for the novelty",
  INFORMACION_NOVEDAD_ADICION: "ADDITION INFORMATION",
  NUMERO_CDP: "CDP Number",
  VALOR_ADICION: "Value Addition",
  VALOR_DESEMBOLSADO: "Value disbursed",
  FECHA_ADICION: "Date Addition",
  NUEVO_VALOR_CONTRATO: "New Contract Value",
  VALOR_ADICION_TEXTO: "Value Addition in Letters",
  NUEVO_VALOR_ADICION: "New Value in Letters",
  INFORMACION_NOVEDAD_PRORROGA: "INFORMATION OF EXTENSION",
  TIEMPO_PRORROGA: "Time Extension (Days)",
  TIEMPO_PRORROGA_PLACEHOLDER: "In days",
  FECHA_PRORROGA: "Date Extension",
  NUEVO_PLAZO_CONTRATO: "New Term of Agreement",
  NUEVO_PLAZO_CONTRATO_PLACEHOLDER: "New contract term (In months)",
  MENSAJE_MESES: "MONTHS AND",
  MESES: "MONTHS",
  MES: "MONTH",
  DIAS: "DAYS",
  DIA: "DAY",
  UN: "ONE",
  DOS: "TWO",
  TRES: "THREE",
  CUATRO: "FOUR",
  CINCO: "FIVE",
  SEIS: "SIX",
  SIETE: "SEVEN",
  OCHO: "EIGHT",
  NUEVE: "NINE",
  DIEZ: "TEN",
  ONCE: "ELEVEN",
  DOCE: "TWELVE",
  TRECE: "THIRTEEN",
  CATORCE: "FOURTEEN",
  QUINCE: "FIFTEEN",
  DIECISEIS: "SIXTEEN",
  DIECISIETE: "SEVENTEEN",
  DIECIOCHO: "EIGHTEEN",
  DIECINUEVE: "NINETEEN",
  DIECI: "DIEZ Y",
  VEINTE: "TWENTY",
  VEINTI: "TWENTY-",
  TREINTA: "THIRTY",
  CUARENTA: "FORTY",
  CINCUENTA: "FIFTY",
  SESENTA: "SIXTY",
  SETENTA: "SEVENTY",
  OCHENTA: "EIGHTY",
  NOVENTA: "NINETY",
  Y: "-",
  CIENTO: "ONE HUNDRED AND ",
  CIEN: "ONE HUNDRED",
  DOSCIENTOS: "TWO HUNDRED ",
  TRESCIENTOS: "THREE HUNDRED ",
  CUATROCIENTOS: "FOUR HUNDRED ",
  QUINIENTOS: "FIVE HUNDRED ",
  SEISCIENTOS: "SIX HUNDRED ",
  SETECIENTOS: "SEVEN HUNDRED ",
  OCHOCIENTOS: "EIGHT HUNDRED ",
  NOVECIENTOS: "NINE HUNDRED ",
  UNMIL: "ONE THOUSAND",
  MIL: "THOUSAND",
  UNMILLON: "ONE MILLION",
  MILLONES: "MILLIONS",
  PESOS: "COLOMBIAN PESOS",
  PESO: "COLOMBIAN PESO",
  CON: "WITH ",
  CERO: "ZERO ",

  //ACTA DE CESION
  ACTA_CESION: "ACT OF ASSIGNMENT",
  INFORMACION:"INFORMATION",
  NO_REGISTRA:"Do not record information",
  VALOR_CONTRATO:"Contract value",
  CONTRATANTE:"Contracting party",
  CONTRATISTA:"Contractor",
  ORDENADOR_DE_GASTO:"Expense authorizer",
  CEDULA_CESIONARIO:"Assignee identification",
  NUMERO_OFICIO:"Purpose number",
  NUMERO_OFICIO_ESTADO_CUENTAS:"Account state purpose number",
  FECHA_OFICIO:"Purpose date",
  FECHA_CESION:"Assignment date",
  PERSONA_NATURAL: "Natural",
  OTRAS_OBSERVACIONES:"Other observations",
  INFORMACION_CESIONARIO:"ASSIGNEE INFORMATION",
  SELECCIONAR_CESIONARIO:"Select assignee",
  ACTA_REINICIO:"ACT OF RESTART",
  FECHA_SUSPENSION:"Suspension date",
  FECHA_REINICIO:"Restart date",
  PERIODO_SUSPENSION:"Suspension term (Days)",
  ACTA_SUSPENSION:"SUSPENSION ACT",
  MOTIVO_SUSPENSION:"Suspension reason",
  CAMPO_REQUERIDO:"This field is required",

  //ALERTAS
  TITULO_ERROR:"There has been mistakes in the form",
  TITULO_ADVERTENCIA:"Warning",
  DESCRIPCION_ADVERTENCIA: "First you must select a type of novelty!",
  DESCRIPCION_ADVERTENCIA_ADICION: "The value of the addition can not exceed 50% of the value of the contract.",
  DESCRIPCION_ADVERTENCIA_PRORROGA: "The value of the extension can not exceed 50% of the contract execution time.",
  DESCRIPCION_ERROR:"Please fill all mandatory fields in the form",
  TITULO_BUEN_TRABAJO:"Good Job!",
  DESCRIPCION_INICIO:"It has been succesfully registered the novelity of 'Home Act'<br>for the contract # ",
  DESCRIPCION_INICIO_1:"The status of this contract was updated to 'Execution'.",
  DESCRIPCION_ADICION:"It has been succesfully registered the novelity of 'Adition'<br>for the contract # ",
  DESCRIPCION_PRORROGA:"It has been succesfully registered the novelity of 'Extension'<br>for the contract # ",
  DESCRIPCION_ADICION_PRORROGA:"It has been succesfully registered the novelity of 'Adition and Extension'<br>for the contract # ",
  DESCRIPCION_INICIO_ERROR_FECHA:"The end date must be greater than the start date!",
  DESCRIPCION_CESION:"It has been succesfully registered the novelity of assignment for the contract # ",
  DESCRIPCION_SUSPENSION:"It has been succesfully registered the novelity of suspension for the contract # ",
  DESCRIPCION_REINICIO:"It has been succesfully registered the novelity of restart for the contract # ",
  DESCRIPCION_ACTA_CESION:"Initial act for contract transferee",
  ANIO:" validity "
};

angular.module('contractualClienteApp')
  .config(function($translateProvider) {
    $translateProvider
      .translations("es", text_es)
      .translations("en", text_en);
    $translateProvider.preferredLanguage("es");
    $translateProvider.useSanitizeValueStrategy("sanitizeParameters");
  });
