"use strict";

/**
 * @ngdoc function
 * @name contractualClienteApp.decorator:TextTranslate
 * @description
 * # TextTranslate
 * Decorator of the contractualClienteApp
 */
var text_es = {
  BTN: {
    VER: "Ver",
    SELECCIONAR: "Seleccionar",
    CANCELAR: "Cancelar",
    CONFIRMAR: "Confirmar",
    AGREGAR: "Agregar",
    REGISTRAR: "Registrar",
    SOLICITAR_RP:"Solicitar RP",
    QUITAR_RUBRO: "Quitar",
    VER_SEGUIMIENTO_FINANCIERO:"Ver seguimiento financiero",
    BUSCAR: "Buscar",
  },
  TITULO: "GENERATOR-OAS",
  MENSAJE_INICIAL: "Ahora puede comenzar con el desarrollo ...",
  NECESIDADES: "Necesidades",
  NECESIDAD: "Necesidad",
  SOLICITUD: "Solicitud",
  //SOLICITUD RP
  ERROR: "Error",
  SALIR:"Salir",
  VOLVER_CONTRATOS: "Volver a contratos",
  NUMERO_SOLICITUD:"Número solicitud",
  INSERCION_RP:"Se insertó correctamente la solicitud del registro presupuestal con los siguientes datos",
  VIGENCIA_SOLICITUD: "Vigencia solicitud",
  FECHA_SOLICITUD: "Fecha solicitud",
  NUMERO_CONTRATO: "Número contrato",
  SELECCIONE_UNA_VIGENCIA:"Seleccione una vigencia diferente",
  RESPONSABLE_DOCUMENTO: "Responsable documento",
  RESPONSABLE: "Responsable",
  DATOS_APROPIACIONES: "Datos de las apropiaciones",
  MODALIDAD_SELECCION: "Modalidad Selección",
  CONTRATO: "Contrato",
  VIGENCIA_CONTRATO: "Vigencia contrato",
  FUENTE:"Fuente",
  SOLICITUD_PERSONAS:"Contratos para solicitud del registro presupuestal",
  VIGENCIA_ACTUAL:"Vigencia Actual ",
  VIGENCIA_SELECCIONADA:"Vigencia Seleccionada ",
  SELECCION_CDP:"Selección de CDP",
  UNIDAD_EJECUTORA:"Unidad ejecutora",
  ESTADO:"Estado",
  SELECCION_COMPROMISO:"Selección de Compromiso",
  SOLICITUD_RP: "Solicitud Registro Presupuestal",
  DATOS_RP:"Datos del Registro Presupuestal",
  BENEFICIARIO:"Beneficiario",
  NOMBRE_CONTRATISTA: "Nombre",
  DOCUMENTO_CONTRATISTA: "No Documento",
  NOMBRE: "Nombre",
  CONTRATO: "Contrato",
  FUENTE_FINANCIAMIENTO: "Fuente Financiamiento",
  VALOR: "Valor",
  COMPROMISO: "Compromiso",
  NUMERO:"Número",
  VIGENCIA:"Vigencia",
  COMPROMISO_TIPO:"Tipo",
  VALOR_RP:"Valor registro presupuestal",
  SALDO_AP:"Saldo apropiación",
  CDP:"CDP",
  CODIGO: "Codigo",
  CONSECUTIVO:"Consecutivo",
  OBJETIVO:"Objetivo",
  OBJETO:"Objeto",
  ORDENADOR:"Ordenador",
  //SEGUMIENTO FINANCIERO
  SEGUIMIENTO_FINANCIERO:"Seguimiento financiero del contrato",
  DATOS_CONTRATO:"Datos contrato",
  ORDENES_PAGO: "Ordenes pago",
  ESTADISTICAS : "Estadisticas",
  DATOS_FINANCIEROS_CONTRATO: "Datos financieros del contrato",
  DATOS_CONTRATISTA: "Datos contratista",
  APELLIDOS: "Apellidos",
  NOMBRES: "Nombres",
  TIPO_DOCUMENTO: "Tipo documento",
  NUMERO_DOCUMENTO : "No documento",
  FECHA_INICIO:"Fecha inicio",
  FECHA_FIN:"Fecha fin",
  DATOS_REGISTRO_PRESUPUESTAL:"Datos del registro presupuestal",
  NUMERO_REGISTRO_PRESUPUESTAL: "No RP",
  NOMBRE_REGISTRO_PRESUPUESTAL: "Nombre RP",
  NUMERO_DISPONIBILIDAD: "No CDP",
  NOMBRE_DISPONIBILIDAD: "Nombre CDP",
  ORDEN_PAGO: "Orden pago",
  FECHA_ORDEN: "Fecha orden",
  VALOR_BRUTO: "Valor bruto",
  LINEA_ORDEN_PAGO:"Linea del tiempo de ordenes de pago",
  ESTADISTICAS_GENERALES: "Estadisticas generales",
  VALOR_TOTAL_CONTRATO: "Valor total contrato",
  VALOR_MENSUAL: "Valor mensual",
  VALOR_TOTAL_PAGADO:"Valor total pagado",
  VALOR_RESTANTE:"Valor restante",
  PORCENTAJE_PAGADO:"Porcentaje pagado",
  PORCENTAJE_RESTANTE:"Porcentaje restante",
  GRAFICO_BARRAS_CONTRATO:"Grafico de barras del contrato",
  CARGO:"Cargo",
  //SEGUIMIENTO LEGAL
  NOVEDADES: "Novedades",
  SEGUIMIENTO_LEGAL: "Seguimiento Legal",
  SELECCIONE_UNA_NOVEDAD: "Por favor seleccione la novedad",
  CREAR_NOVEDAD_ADICION_PRORROGA: "Crear Novedad de Adición y/o Prorroga",
  CREAR_ACTA_INICIO: "Crear Acta de Inicio",
  CREAR_NOVEDAD_SUSPENSION: "Crear Novedad de Suspensión",
  CREAR_NOVEDAD_REINICIO: "Crear Novedad de Reinicio",
  CREAR_NOVEDAD_CESION: "Crear Novedad de Cesión",
  CREAR_NOVEDAD_LIQUIDACION: "Crear Novedad de Liquidación",
  CREAR_NOVEDAD_TERMINACION_ANTICIPADA: "Crear Novedad de Terminación Anticipada",
  CREAR_NOVEDAD_OTRO_SI_MODIFICATORIO: "Crear Otro Sí Modificatorio",
  CREAR_NOVEDAD_OTRO_SI_ACLARATORIO: "Crear Otro Sí Aclaratorio",
  //ACTA INICIO
  ACTA_INICIO: "ACTA DE INICIO",
  INFORMACION: "INFORMACIÓN",
  PLAZO_MESES: "Plazo (en meses)",
  SUPERVISOR: "Supervisor",
  NO_REGISTRA: "No registra",
  NUMERO_POLIZA: "Número de poliza",
  FECHA_EXPEDICION_POLIZA: "Fecha Expedición de Póliza",
  FECHA_APROBACION_POLIZA: "Fecha Aprobación de Póliza",
  INFORMACION_NOVEDAD: "INFORMACIÓN DE LA NOVEDAD",
  INVENTARIO: "INVENTARIO",
  TIPO_BIEN: "TIPO DE BIEN",
  PLACA: "PLACA",
  DESCRIPCION: "DESCRIPCIÓN",
  SEDE: "SEDE",
  DEPENDENCIA: "DEPENDENCIA",
  ESTADO_DEL_BIEN: "ESTADO DEL BIEN",
  //ACTA DE ADICION/PRORROGA
  ACTA_ADICION_PRORROGA: "ACTA DE ADICIÓN/PRORROGA",
  TIPO_CONTRATO: "Tipo de contrato",
  PLAZO_INICIAL_MESES: "Plazo inicial (En meses)",
  FECHA_INICIACION: "Fecha de Iniciación",
  ADICION: "Adición",
  PRORROGA: "Prórroga",
  MOTIVO: "Motivo",
  MOTIVO_NOVEDAD: "Ingrese aqui el motivo de la novedad",
  INFORMACION_NOVEDAD_ADICION: "INFORMACIÓN DE ADICIÓN",
  NUMERO_CDP: "Número CDP",
  VALOR_ADICION: "Valor Adición",
  FECHA_ADICION: "Fecha Adición",
  NUEVO_VALOR_CONTRATO: "Nuevo Valor del Contrato",
  INFORMACION_NOVEDAD_PRORROGA: "INFORMACIÓN DE PRÓRROGA",
  TIEMPO_PRORROGA: "Tiempo Prórroga",
  TIEMPO_PRORROGA_PLACEHOLDER: "En días",
  FECHA_PRORROGA: "Fecha Prórroga",
  NUEVO_PLAZO_CONTRATO: "Nuevo Plazo del Contrato",
  NUEVO_PLAZO_CONTRATO_PLACEHOLDER: "Nuevo plazo del contrato (En meses)",
  ACTA_CESION: "ACTA DE CESIÓN",
  INFORMACION:"INFORMACIÓN",
  NO_REGISTRA:"No Registra",
  VALOR_CONTRATO:"Valor del contrato",
  CONTRATANTE:"Contratante",
  CONTRATISTA:"Contratista",
  ORDENADOR_DE_GASTO:"Ordenador de gasto",
  CEDULA_CESIONARIO:"Cédula cesionario",
  TIPO_PERSONA: "Tipo persona",
  NUMERO_OFICIO:"Número oficio",
  FECHA_OFICIO:"Fecha oficio",
  FECHA_CESION:"Fecha cesión",
  OTRAS_OBSERVACIONES:"Otras observaciones",
  INFORMACION_CESIONARIO:"INFORMACIÓN CESIONARIO",
  SELECCIONAR_CESIONARIO:"Seleccionar cesionario",
  ACTA_REINICIO:"ACTA DE REINICIO",
  FECHA_SUSPENSION:"Fecha suspension",
  FECHA_REINICIO:"Fecha reinicio",
  PERIODO_SUSPENSION:"Periodo suspension (Días)",
  ACTA_SUSPENSION:"ACTA DE SUSPENSIÓN",
  MOTIVO_SUSPENSION:"Motivo de suspensión",
  CAMPO_REQUERIDO:"Este campo es obligatorio"
};

var text_en = {
  TITULO: "GENERATOR-OAS",
  MENSAJE_INICIAL: "Now get to start to develop ...",
  NECESIDADES: "Needs",
  NECESIDAD: "Need",
  BTN: {
    VER: "See",
    SELECCIONAR: "Choose",
    CANCELAR: "Cancel",
    CONFIRMAR: "Confirm",
    AGREGAR: "Add",
    REGISTRAR: "Register",
    SOLICITAR_RP:"RP request",
    QUITAR_RUBRO: "Delete",
    VER_SEGUIMIENTO_FINANCIERO:"See financial monitoring",
    BUSCAR: "Search",
  },
  //SOLICITUD RP
  ERROR: "Error",
  SALIR:"Exit",
  VOLVER_CONTRATOS: "Back to contracts",
  NUMERO_SOLICITUD:"Request number",
  INSERCION_RP:"The budget register request was insert correctly with the following data:",
  VIGENCIA_SOLICITUD: "Request validity",
  FECHA_SOLICITUD: "Request date",
  NUMERO_CONTRATO: "Contract number",
  RESPONSABLE_DOCUMENTO: "Person responsible identification",
  SELECCIONE_UNA_VIGENCIA:"Choose a diferent validity",
  RESPONSABLE: "Person responsible",
  DATOS_APROPIACIONES: "Appropiation data",
  MODALIDAD_SELECCION: "Selection method",
  CONTRATO: "Contract",
  VIGENCIA_CONTRATO: "Contract validity",
  FUENTE:"Source",
  TIPO_PERSONA: "Person type",
  SOLICITUD_PERSONAS:"Contracts for budget registers",
  VIGENCIA_ACTUAL:"Current validity",
  VIGENCIA_SELECCIONADA:"Chosen validity ",
  SELECCION_CDP:"CDP choise",
  UNIDAD_EJECUTORA:"Performer unity",
  ESTADO:"State",
  SELECCION_COMPROMISO:"Agreement choose",
  SOLICITUD_RP: "Budget register request",
  DATOS_RP:"Buget register data",
  BENEFICIARIO:"Beneficiary",
  NOMBRE_CONTRATISTA: "Name",
  DOCUMENTO_CONTRATISTA: "Identification",
  NOMBRE: "Name",
  CONTRATO: "Contract",
  FUENTE_FINANCIAMIENTO: "Funding source",
  VALOR: "Value",
  COMPROMISO: "Agreement",
  NUMERO:"Number",
  VIGENCIA:"Validity",
  COMPROMISO_TIPO:"Tipe",
  VALOR_RP:"Budget register value",
  SALDO_AP:"Appropiation reminder",
  CDP:"CDP",
  CODIGO: "Code",
  CONSECUTIVO:"Consecutive",
  OBJETIVO:"Objective",
  OBJETO:"Object",
  ORDENADOR:"Authorizer",
  //SEGUMIENTO FINANCIERO
  SEGUIMIENTO_FINANCIERO:"Financial monitoring of the contract",
  DATOS_CONTRATO:"Contract data",
  ORDENES_PAGO: "Pay orders",
  ESTADISTICAS : "Statistics",
  DATOS_FINANCIEROS_CONTRATO: "Financial data of the contract",
  DATOS_CONTRATISTA: "Contractor data",
  APELLIDOS: "Surnames",
  NOMBRES: "Names",
  TIPO_DOCUMENTO: "Identification type",
  NUMERO_DOCUMENTO : "Document number",
  FECHA_INICIO:"Start date",
  FECHA_FIN:"End date",
  DATOS_REGISTRO_PRESUPUESTAL:"Budget register data",
  NUMERO_REGISTRO_PRESUPUESTAL: "Budget register number",
  NOMBRE_REGISTRO_PRESUPUESTAL: "Budget register name",
  NUMERO_DISPONIBILIDAD: "Availability number",
  NOMBRE_DISPONIBILIDAD: "Availability name",
  ORDEN_PAGO: "Pay order",
  FECHA_ORDEN: "Order date",
  VALOR_BRUTO: "Gross value",
  LINEA_ORDEN_PAGO:"Pay orders timeline",
  ESTADISTICAS_GENERALES: "General statistics",
  VALOR_TOTAL_CONTRATO: "Contract total value",
  VALOR_MENSUAL: "Monthly value",
  VALOR_TOTAL_PAGADO:"Paid total value",
  VALOR_RESTANTE:"Remaining value",
  PORCENTAJE_PAGADO:"Paid percentage",
  PORCENTAJE_RESTANTE:"Remaining percentage",
  GRAFICO_BARRAS_CONTRATO:"Contract bar graph",
  CARGO:"Post",
  //SEGUIMIENTO LEGAL
  NOVEDADES: "Novelty",
  SEGUIMIENTO_LEGAL: "Legal Tracking",
  SELECCIONE_UNA_NOVEDAD: "Please select the novelty",
  CREAR_NOVEDAD_ADICION_PRORROGA: "Create Novelty Addition and / or Extension",
  CREAR_ACTA_INICIO: "Create Minutes of Beginning",
  CREAR_NOVEDAD_SUSPENSION: "Create Novelty Suspension",
  CREAR_NOVEDAD_REINICIO: "Create Novelty Restart",
  CREAR_NOVEDAD_CESION: "Create Novelty Assignment",
  CREAR_NOVEDAD_LIQUIDACION: "Create Novelty Clearance",
  CREAR_NOVEDAD_TERMINACION_ANTICIPADA: "Create Novelty Early Termination",
  CREAR_NOVEDAD_OTRO_SI_MODIFICATORIO: "Create Other Yes Modification",
  CREAR_NOVEDAD_OTRO_SI_ACLARATORIO: "Create Other Yes Clear",
  //ACTA INICIO
  ACTA_INICIO: "HOME ACT",
  INFORMACION: "INFORMATION",
  PLAZO_MESES: "Term (in months)",
  SUPERVISOR: "Supervisor",
  NO_REGISTRA: "Not register",
  NUMERO_POLIZA: "Policy number",
  FECHA_EXPEDICION_POLIZA: "Date Policy Issue",
  FECHA_APROBACION_POLIZA: "Date Policy Approval",
  INFORMACION_NOVEDAD: "NOVELTY INFORMATION",
  INVENTARIO: "INVENTORY",
  TIPO_BIEN: "TYPE OF PROPERTY",
  PLACA: "LICENSE PLATE",
  DESCRIPCION: "DESCRIPTION",
  SEDE: "HEADQUARTERS",
  DEPENDENCIA: "DEPENDENCE",
  ESTADO_DEL_BIEN: "STATE OF POSSESSION",
  //ACTA DE ADICION/PRORROGA
  ACTA_ADICION_PRORROGA: "ADDITION / EXTENSION ACT",
  TIPO_CONTRATO: "Type of contract",
  PLAZO_INICIAL_MESES: "Initial period (In months)",
  FECHA_INICIACION: "Date of Initiation",
  ADICION: "Addition",
  PRORROGA: "Extension",
  MOTIVO: "Reason",
  MOTIVO_NOVEDAD: "Enter here the reason for the novelty",
  INFORMACION_NOVEDAD_ADICION: "ADDITION INFORMATION",
  NUMERO_CDP: "CDP Number",
  VALOR_ADICION: "Value Addition",
  FECHA_ADICION: "Date Addition",
  NUEVO_VALOR_CONTRATO: "New Contract Value",
  INFORMACION_NOVEDAD_PRORROGA: "INFORMATION OF EXTENSION",
  TIEMPO_PRORROGA: "Time Extension",
  TIEMPO_PRORROGA_PLACEHOLDER: "In days",
  FECHA_PRORROGA: "Date Extension",
  NUEVO_PLAZO_CONTRATO: "New Term of Agreement",
  NUEVO_PLAZO_CONTRATO_PLACEHOLDER: "New contract term (In months)",
  ACTA_CESION: "ACT OF ASSIGNMENT",
  INFORMACION:"INFORMATIÓN",
  NO_REGISTRA:"Do not record information",
  VALOR_CONTRATO:"Contract value",
  CONTRATANTE:"Contracting party",
  CONTRATISTA:"Contractor",
  ORDENADOR_DE_GASTO:"Expense authorizer",
  CEDULA_CESIONARIO:"Assignee identification",
  NUMERO_OFICIO:"Purpose number",
  FECHA_OFICIO:"Purpose date",
  FECHA_CESION:"Assignment date",
  OTRAS_OBSERVACIONES:"Other observations",
  INFORMACION_CESIONARIO:"ASSIGNEE INFORMATION",
  SELECCIONAR_CESIONARIO:"Select assignee",
  ACTA_REINICIO:"ACT OF RESTART",
  FECHA_SUSPENSION:"Suspension date",
  FECHA_REINICIO:"Restart date",
  PERIODO_SUSPENSION:"Suspension term (Days)",
  ACTA_SUSPENSION:"SUSPENSION ACT",
  MOTIVO_SUSPENSION:"Suspension reason",
  CAMPO_REQUERIDO:"This field is required"
};

angular.module('contractualClienteApp')
  .config(function($translateProvider) {
    $translateProvider
      .translations("es", text_es)
      .translations("en", text_en);
    $translateProvider.preferredLanguage("es");
    $translateProvider.useSanitizeValueStrategy("sanitizeParameters");
  });
